Updated lev syops for change of monarch title
UKHomeOffice/keycloak-theme-govuk pull request #62
Opened 2023-10-04 11:28 UTC by aarongill1

2023-10-04 11:29 UTC, sureshnature commented
The email address you have sent to ***@***.*** is for a legacy domain and will shortly be removed.

Please update your address book and send to the same address but having removed .gsi. from the domain part.

Mail to the legacy addresses will stop working in a few weeks.

2023-10-04 11:30 UTC, conwubiko commented
The email address you have sent to ***@***.*** is for a legacy domain and will shortly be removed.

Please update your address book and send to the same address but having removed .gsi. from the domain part.

Mail to the legacy addresses will stop working in a few weeks.

2023-10-04 11:39 UTC, ashley-bickerstaff-homeoffice requested changes
Can you check that the versioning won't be an issue?

2023-10-04 11:39 UTC, ashley-bickerstaff-homeoffice commented on package.json
> +  "version": "2.0.20",
Although the repo homepage says 2.0.19 is the latest, on the releases page, it says that the *.20 tag already exists. Perhaps this should be *.21?

2023-10-04 11:45 UTC, ashley-bickerstaff-homeoffice approved these changes

2023-10-05 13:36 UTC, James-Royds-HO commented on package.json
This version bump isn't needed. Just your changes to your T&Cs

2023-10-05 13:37 UTC, James-Royds-HO approved these changes

2023-10-05 13:59 UTC, merged